export default {
  '.js':    'js',
  '.html':  'html',
  '.css':   'css',
  '.json':  'json',
  '.svg':   'font',
  '.eot':   'font',
  '.woff2': 'font',
  '.ttf':   'font',
  '.woff':  'font',
  '.jpeg':  'image',
  '.jpg':   'image',
  '.tiff':  'image',
  '.raw':   'image',
  '.bmp':   'image',
  '.gif':   'image',
  '.png':   'image',
  '.map':   'map',
  '.gz':    'gz'
};
